apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-cicd
  namespace: hk-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-cicd
  template:
    metadata:
      labels:
        app: jenkins-cicd
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000

        resources:
          requests:
            memory: "2Gi"
            cpu: "512m"
          limits:
            memory: "4Gi"
            cpu: "1"

        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: docker-sock
          mountPath: /var/run/docker.sock
      serviceAccountName: jenkins-sa
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-cicd-pvc-v1
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
