apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ops-ingress
  namespace: hk-jenkins
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jenkins-ops.local
    secretName: jenkins-ops-tls
  rules:
  - host: jenkins-ops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins-ops-service
            port:
              number: 8080
