apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ops-ingress
  namespace: hk-jenkins
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: jenkins-ops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins-ops-service
            port:
              number: 443

