apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-cicd-ingress
  namespace: hk-jenkins
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jenkins-cicd.local
    secretName: jenkins-cicd-tls
  rules:
  - host: jenkins-cicd.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins-cicd-service
            port:
              number: 8080
<<<<<<< HEAD
=======

>>>>>>> ebea91a554ab57c5b1a90ea37bf9adba42c3cdc2
